import React from 'react';
import {createRoot, hydrateRoot} from 'react-dom/client';
import {BrowserRouter} from 'react-router-dom';
import App from './App';
import './styles.css';
const root = document.getElementById('root');
const initialContent = window.__INITIAL_CONTENT__ || null;
const application = <React.StrictMode><BrowserRouter><App initialContent={initialContent}/></BrowserRouter></React.StrictMode>;
if (root.hasAttribute('data-prerendered')) hydrateRoot(root, application);
else createRoot(root).render(application);
